<div class="Panel">
    <div class="Panel-row">
        <label for="title" class="Panel-text">
            Título
        </label> 
        <input
            id="title" 
            name="post_title" 
            type="text"
            autocomplete="off"  
            spellcheck="true" 
            value="<?php echo $post->post_title ?>"
        />
    </div>
    <div class="Panel-row"></div>
</div>

<div class="Panel" style="padding: 10px 0 0 0;">
    <div class="Panel-row" style="margin-bottom: 0;">
    </div>
</div> 