<ul class="Tabs">
    <li class="Tabs-tabItem">
        <a href="#project-tab" id="project-tab-item">
            <i class="Tabs-tabItem-arrow"></i>
            <span>Projeto</span>
        </a>
        <div id="project-tab-panel" class="Tabs-tabPanel">
            <?php require "project-tab/ProjectTab.phtml"; ?>
        </div>
    </li>
    <li class="Tabs-tabItem">
        <a href="#scene-tab" id="scene-tab-item">
            <i class="Tabs-tabItem-arrow"></i>
            <span>Cena</span>
        </a>
        <div id="scene-tab-panel" class="Tabs-tabPanel">
            <?php require "scene-tab/SceneTab.phtml"; ?>
        </div>
    </li>
    <li class="Tabs-tabItem">
        <a href="#settings-tab" id="settings-tab-item">
            <i class="Tabs-tabItem-arrow"></i>
            <span>Configurações</span>
        </a>
        <div id="settings-tab-panel" class="Tabs-tabPanel">
            <?php require "settings-tab/SettingsTab.phtml"; ?>
        </div>
    </li>
</ul>