<span>
    <div class="Panel">
        <div class="Panel-row">
            <label for="ctx-selector" class="Panel-text"> Cena </label>
            <select id="ctx-selector" autocomplete="off"></select>
            <div 
                id="delete-scene-btn"
                class="Button" 
                title="<?php echo htmlentities($help_texts["deleteSceneBtn"], ENT_QUOTES, "UTF-8") ?>"
            >
                <i class="fa fa-trash-o" aria-hidden="true"></i>
            </div>
            <div 
                id="add-scene-btn"
                class="Button" 
                title="<?php echo htmlentities($help_texts["newSceneBtn"], ENT_QUOTES, "UTF-8") ?>"
            >
                <i class="fa fa-plus" aria-hidden="true"></i>
            </div>
        </div>
        <div class="Panel-row">
            <label for="ctx-name" class="Panel-text"> 
                Nome
            </label>
            <input id="ctx-name" type="text" />
        </div>
        <div class="Panel-row">
            <label 
                for="opacity-factor" 
                class="Panel-text" 
                title="<?php echo htmlentities($help_texts["opacityFactor"], ENT_QUOTES, "UTF-8") ?>"
            > 
                Fator de transparência 
            </label>
            <input 
                id="opacity-factor"
                type="number" 
                min="0" 
                max="1"
                step="0.1" 
            />
        </div>
        <div class="Panel-row">
            <label 
                for="scene-render-order" 
                class="Panel-text" 
                title="<?php echo htmlentities($help_texts["sceneRenderOrder"], ENT_QUOTES, "UTF-8") ?>"
            > 
                Ordem de renderização
            </label>
            <input 
                id="scene-render-order"
                type="number" 
                min="0" 
                max="2"
                step="1" 
            />
        </div>
    </div>
    <div id="bg-selector-panel" class="Panel">
        <?php require "selectors/BackgroundSelector.phtml"; ?>
    </div>
    <div id="env-map-selector-panel" class="Panel">
        <?php require "selectors/EnvMapSelector.phtml"; ?>
    </div>
    <div id="fog-selector-panel" class="Panel">
        <?php require "selectors/FogSelector.phtml"; ?>
    </div>

    <div id="properties"> 
        <ul class="Tabs" style="padding-top: 0">
            <li
                style="margin-bottom: 0"
                class="Tabs-tabItem Tabs-tabItem--is-selected"
            >
                <a href="#object-tab" id="object" style="display: inline-block">
                    Objeto
                </a>
            </li>
            <li style="margin-bottom: 0" class="Tabs-tabItem">
                <a
                    href="#geometry-tab"
                    id="geometry"
                    style="display: inline-block"
                >
                    Geometria
                </a>
            </li>
            <li style="margin-bottom: 0" class="Tabs-tabItem">
                <a
                    href="#material-tab"
                    id="material"
                    style="display: inline-block"
                >
                    Material
                </a>
            </li>
        </ul>
        <div class="Panels">
            <div id="object-tab" style="">
                <div class="Panel">
                    <?php require "rows/ObjectRows.phtml"; ?>
                </div>
            </div>

            <div id="geometry-tab" style="display: none">
                <div class="Panel">
                    <?php require "rows/GeometryRows.phtml"; ?>
                </div>
            </div>

            <div id="material-tab" style="display: none">
                <div class="Panel">
                    <?php require "rows/MaterialRows.phtml"; ?>
                </div>
            </div>
        </div>
    </div>
</span>
