<div class="Panel-row">
    <span class="Panel-title" title="<?php echo htmlentities($help_texts["sceneBackground"], ENT_QUOTES, "UTF-8") ?>">
        Pano de fundo
    </span>
</div> 

<div class="Panel-row">
    <label for="bg-type-selector" class="Panel-text">
        Tipo
    </label>

    <select id="bg-type-selector" autocomplete="off"> 
        <?php foreach ($background_types as $value => $label) : ?> 
            <option value="<?php echo $value ?>">
                <?php echo $label ?>
            </option>
        <?php endforeach; ?>
    </select>
</div> 
 
<div class="Panel-row" for-select="bg-type-selector" show-when-value="Color" style="display: none;">
    <label for="bg-color" class="Panel-text">
        Cor
    </label>
    <input id="bg-color" autocomplete="off" type="color" />
</div>

<div class="Panel-row" for-select="bg-type-selector" show-when-value-not="None, Color" style="display: none;">
    <label for="bg-image" class="Panel-text">
        Imagem(ns)
    </label>
    <div id="bg-image" class="Image"></div>
</div>