<?php $scope = "material"; ?>

<div class="Panel-row js-field" id="<?php echo "$scope-type-row" ?>" style="display: none;">
    <label for="material-type-selector" class="Panel-text Panel-item--is30">
        Tipo
    </label>  
    <select 
        id="material-type-selector"
        class="Panel-item--is66" 
        autocomplete="off"
        data-scope="<?php echo $scope ?>" 
        data-type="String" 
        data-option="type"
    >
        <?php foreach ( $materials as $mat_name => $mat ) : ?>
            <option value="<?php echo $mat_name ?>">
                <?php echo $mat["label"] ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>

<div class="Panel-row js-field" id="<?php echo "$scope-uuid-row" ?>" style="display: none;">
    <span class="Panel-text">
        UUID
    </span>
    <input 
        autocomplete="off" 
        data-scope="<?php echo $scope ?>" 
        data-type="String" 
        data-option="uuid"
        disabled
    />
</div>

<div class="Panel-row js-field" id="<?php echo "$scope-name-row" ?>" style="display: none;">
    <label for="<?php echo "$scope-name-field" ?>" class="Panel-text">
        Nome
    </label>
    <input 
        id="<?php echo "$scope-name-field" ?>" 
        autocomplete="off" 
        data-scope="<?php echo $scope ?>" 
        data-type="String" 
        data-option="name"
    />
</div>

<?php foreach ( $material_rows as $row ) : 
    require __DIR__."/../field-templates/{$row["component"]}.phtml";
endforeach; ?>