<div class="Panel-row">
    <label for="env-map-type-selector" class="Panel-text">
        Projeção
    </label>

    <select id="env-map-type-selector" autocomplete="off">
        <?php foreach ($mapping_types as $value => $label) : ?>
            <option value="<?php echo $value ?>">
                <?php echo $label ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>

<div 
    for-select="env-map-type-selector" 
    show-when-value-not="None" 
    class="Panel-row" 
    style="display: none;"
>
    <label class="Panel-text">
        Imagem(ns)
    </label>
    <div id="env-map-image" class="Image"></div>
</div>

<div 
    for-select="env-map-type-selector" show-when-value-not="None, UVMapping" 
    class="Panel-row" style="display: none;"
>
    <label for="env-map-has-refraction" class="Panel-text">
        Refração
    </label>
    <input id="env-map-has-refraction" type="checkbox" /> 
</div>