<span> Grupos </span>
<span data-stat="groups"> 6 </span>

<br />

<span> Objetos </span>
<span data-stat="objects"> 6 </span>

<br />

<span> Geometrias </span>
<span data-stat="geometries"> 6 </span>

<br />

<span> Luzes </span>
<span data-stat="lights"> 6 </span>

<br />

<span> Texturas </span>
<span data-stat="textures"> 6 </span>

<br />

<span class="is-full-width">
	<span> Posição (XYZ) </span>
	<input
		data-stat="coord-x"
		type="number"
		step="1"
		style="
			width: 15%;
			pointer-events: all;
			cursor: pointer;
			color: #fff !important;
			text-align: right;
		"
	/>
	<input
		data-stat="coord-y"
		type="number"
		step="1"
		style="
			width: 15%;
			pointer-events: all;
			cursor: pointer;
			color: #fff !important;
			text-align: right;
		"
	/>
	<input
		data-stat="coord-z"
		type="number"
		step="1"
		style="
			width: 15%;
			pointer-events: all;
			cursor: pointer;
			color: #fff !important;
			text-align: right;
		"
	/>
</span>