<div 
	id="zoom-in-btn"
	class="Viewport-toolbar-button" 
	title="Aumentar zoom (+)"
>
	<i class="fa fa-plus" aria-hidden="true"></i>
</div>
<div 
	id="zoom-out-btn"
	class="Viewport-toolbar-button" 
	title="Diminuir zoom (-)"
>
	<i class="fa fa-minus" aria-hidden="true"></i>
</div>

<div 
	class="Viewport-toolbar-button Viewport-toolbar-button--is-selected" 
	data-mode="translate"
	title="Mover (w)"
>
	<i class="fa fa-arrows" aria-hidden="true"></i>
</div>
<div 
	class="Viewport-toolbar-button" 
	data-mode="rotate" 
	title="Rotacionar (e)"
>
	<i class="fa fa-refresh" aria-hidden="true"></i>
</div>
<div 
	class="Viewport-toolbar-button" 
	data-mode="scale" 
	title="Escalar (r)"
>
	<i class="fa fa-expand" aria-hidden="true"></i>
</div>