<div class="Menubar-item">
    <span class="Menubar-item-title">
        Editar
    </span>

    <div class="HoverDropdown">
        <div id="undo-btn" class="HoverDropdown-item is-inactive">
            Desfazer (Ctrl+Z)
        </div>
        <div id="redo-btn" class="HoverDropdown-item is-inactive">
            Refazer (Ctrl+Y)
        </div>
        <div id="clear-btn" class="HoverDropdown-item is-inactive">
            Limpar Histórico
        </div>

        <hr />

        <div id="clone-btn" class="HoverDropdown-item is-inactive" title="Em breve!">
            Clonar
        </div>
        <div id="delete-btn" class="HoverDropdown-item is-inactive">
            Deletar (Del)
        </div>
    </div>
</div>
