<header id="menubar" class="Menubar">
    <?php require "FileItem.phtml" ?>

    <?php require "EditItem.phtml" ?>
    
    <?php require "AddItem.phtml" ?>
    
    <div class="Menubar-item">
        <span class="Menubar-item-title">
            Visualizar
        </span>
        <div class="HoverDropdown">
            <div id="toggle-theme-btn" class="HoverDropdown-item">
                em tema escuro
            </div>
            <div id="toggle-fullscreen-btn" class="HoverDropdown-item">
                em tela cheia
            </div>
        </div>
    </div>
                
    <div class="Menubar-item Menubar-item--isRight">
        <span class="Menubar-item-title is-transparent" style="cursor: default;">
            Criador de Plantas 3D
        </span>
    </div>
</header>