<div id="<?php echo "$scope-{$row["attribute"]}-row" ?>" style="display: none;">
    <hr />
    
    <div class="Panel-row"> 
        <span 
            class="Panel-title" 
            <?php if ( isset($help_texts[ $row["attribute"] ]) ) : ?>
                title="<?php echo htmlentities($help_texts[ $row["attribute"] ], ENT_QUOTES, "UTF-8") ?>"
            <?php endif; ?>
        >
            <?php echo $row["label"] ?>
        </span>
    </div> 
     
    <div class="Panel-row">
        <label for="<?php echo "$scope-{$row["attribute"]}-enable" ?>" class="Panel-text">
            Habilitar 
        </label>
        <input 
            id="<?php echo "$scope-{$row["attribute"]}-enable" ?>"
            type="checkbox" 
            disabled 
        />
    </div>
    
    <?php if ( $row["has_types"] ) : ?>
        <div class="Panel-row">
            <label for="<?php echo "$scope-{$row["attribute"]}-mappingSelector" ?>" class="Panel-text">
                Projeção
            </label> 
            <select id="<?php echo "$scope-{$row["attribute"]}-mappingSelector" ?>" autocomplete="off">
                <?php foreach ($mapping_types as $value => $label) : ?>
                    <option value="<?php echo $value ?>">
                        <?php echo $label ?>
                    </option>
                <?php endforeach; ?>
            </select> 
        </div> 
    <?php endif; ?>
    
    <div 
        class="Panel-row" 
        for-select="<?php echo "$scope-{$row["attribute"]}-mappingSelector" ?>" 
        show-when-value-not="None" <?php echo $row["has_types"] ? 'style="display: none;"' : "" ?>
    >
        <label for="<?php echo "$scope-{$row["attribute"]}-uploader" ?>" class="Panel-text">
            Imagem(ns)
        </label> 
        
        <div id="<?php echo "$scope-{$row["attribute"]}-uploader" ?>" class="Image"></div>
    </div>
            
    <?php if ( $row["has_refr"] ) : ?>
        <div 
            class="Panel-row" for-select="<?php echo "$scope-{$row["attribute"]}-mappingSelector" ?>" 
            show-when-value-not="None, UVMapping" style="display: none;"
        >
            <label for="<?php echo "$scope-{$row["attribute"]}-enableRefraction" ?>" class="Panel-text">
                Habilitar refração
            </label>
            <input id="<?php echo "$scope-{$row["attribute"]}-enableRefraction" ?>" type="checkbox" />
        </div>
        <div 
            class="Panel-row" for-select="<?php echo "$scope-{$row["attribute"]}-mappingSelector" ?>" 
            show-when-value-not="None, UVMapping" style="display: none;"
        >
            <label for="<?php echo "$scope-{$row["attribute"]}-refractionRatio" ?>" class="Panel-text">
                Taxa de Refração
            </label>
            <input 
                id="<?php echo "$scope-{$row["attribute"]}-refractionRatio" ?>" 
                type="number" 
                data-scope="<?php echo $scope ?>" 
                data-option="refractionRatio" 
                data-type="Float" 
                step="0.01" min="0" max="1"
            />
        </div>
    <?php endif; ?>
        
    <textarea 
        style="display: none;" 
        data-scope="<?php echo $scope ?>" 
        data-option="<?php echo $row["attribute"] ?>" 
        data-type="JSON"
    ></textarea>
</div>