<?php $scope = "object"; ?>

<div class="Panel-row js-field" id="<?php echo "$scope-type-row" ?>" style="display: none;">
    <span class="Panel-text">
        Tipo
    </span>
    <span class="Panel-text" data-option="type" data-scope="<?php echo $scope ?>" data-type="String">
        {{objectType}}
    </span>
</div>
 
<div class="Panel-row js-field" id="<?php echo "$scope-uuid-row" ?>" style="display: none;">
    <span class="Panel-text">
        UUID
    </span>
    <input 
        type="text"
        autocomplete="off" 
        data-option="uuid" 
        data-scope="<?php echo $scope ?>" 
        data-type="String" 
        disabled 
    />
</div>

<div class="Panel-row js-field" id="<?php echo "$scope-name-row" ?>" style="display: none;">
    <label for="<?php echo "$scope-name-field" ?>" class="Panel-text">
        Nome
    </label>
    <input 
        id="<?php echo "$scope-name-field" ?>" 
        type="text"
        autocomplete="off" 
        data-option="name" 
        data-scope="<?php echo $scope ?>" 
        data-type="String"
    />
</div>

<?php foreach ( $object_rows as $row ) : 
    require __DIR__."/../field-templates/{$row["component"]}.phtml";
endforeach; ?>

<div class="Panel-row js-field" id="<?php echo "$scope-shadow-row" ?>" style="display: none;">
    <span class="Panel-text">
        Sombra
    </span>
    <label style="margin-right: 4px;">
        <input 
            type="checkbox" data-type="Bool" 
            data-scope="<?php echo $scope ?>" data-option="castShadow" 
        />
        <span class="Panel-text" style="width: 15%; margin-left: 3px;">
            lança
        </span>
    </label>
    <label style="margin-right: 4px;">
        <input 
            type="checkbox" data-type="Bool" 
            data-scope="<?php echo $scope ?>" data-option="receiveShadow" 
        />
        <span class="Panel-text" style="width: 15%; margin-left: 3px;">
            recebe
        </span>
    </label>
</div>

<div class="Panel-row js-field" id="<?php echo "$scope-renderOrder-row" ?>" style="display: none;">
    <label for="<?php echo "$scope-renderOrder-field" ?>" class="Panel-text">
        Ordem de Renderização
    </label>
    <input 
        id="<?php echo "$scope-renderOrder-field" ?>" 
        class="Panel-item--is16"
        type="number" 
        step="1" 
        autocomplete="off" 
        data-type="Int" 
        data-scope="<?php echo $scope ?>" 
        data-option="renderOrder" 
    />
</div>