<div class="Panel-row" id="<?php echo "$scope-{$row["attribute"]}-row" ?>" style="display: none;">
    <label 
        for="<?php echo "$scope-{$row["attribute"]}-field" ?>" 
        class="Panel-text" 
        <?php if ( isset($help_texts[ $row["attribute"] ]) ) : ?>
            title="<?php echo htmlentities($help_texts[ $row["attribute"] ], ENT_QUOTES, "UTF-8") ?>"
        <?php endif; ?>
    >
        <?php echo $row["label"] ?>
    </label>
    <input 
        id="<?php echo "$scope-{$row["attribute"]}-field" ?>" 
        type="checkbox" 
        data-scope="<?php echo $scope ?>" 
        data-type="Bool" 
        data-option="<?php echo $row["attribute"] ?>"
    />
</div>