<div class="Panel-row" id="<?php echo "$scope-{$row["attribute"]}-row" ?>" style="display: none;">
    <label 
        for="<?php echo "$scope-{$row["attribute"]}-selector" ?>" 
        class="Panel-text"
        <?php if ( isset($help_texts[ $row["attribute"] ]) ) : ?>
            title="<?php echo htmlentities($help_texts[ $row["attribute"] ], ENT_QUOTES, "UTF-8") ?>"
        <?php endif; ?>
    >
        <?php echo $row["label"] ?>
    </label>
    
    <select 
        id="<?php echo "$scope-{$row["attribute"]}-selector" ?>" 
        autocomplete="off" 
        data-scope="<?php echo $scope ?>" 
        data-type="String" 
        data-option="<?php echo $row["attribute"] ?>"
    >
        <?php foreach ( $row["options"] as $opt ) : ?>
            <option value="<?php echo $opt["value"] ?>">
                <?php echo $opt["text"] ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>