<div id="editor" class="Editor" data-theme="light">
    <!-- Barra de Utilidades --> 
    <?php require_once "menubar/Menubar.phtml" ?>
    <!-- Planta 3D será visível aqui -->
    <?php require_once "viewport/Viewport.phtml" ?>
    <!-- Outras utilidades na sidebar -->
    <?php require_once "sidebar/Sidebar.phtml" ?>
    <footer class="Footer">
        <!-- Interação Servidor-Cliente -->
        <?php require_once "config/ConfigFields.phtml" ?>
    </footer>
</div>  