<div class="Panel">
    <div class="Panel-row">
        <label for="title" class="Panel-text">
            Título
        </label> 
        <input
            id="title" 
            name="post_title" 
            type="text"
            autocomplete="off"  
            spellcheck="true" 
            value="<?php echo $post->post_title ?>"
        />
    </div>
    <div class="Panel-row"></div>
</div>
  
<div class="Panel">
    <div class="Panel-row">
        <span class="Panel-title">
            Renderizador
        </span>
    </div>
    
    <div class="Panel-row">
        <label 
            for="antialias-toggler" 
            class="Panel-text" 
            title="<?php echo htmlentities($help_texts["antialias"], ENT_QUOTES, "UTF-8") ?>"
        >
            Anti-aliasing
        </label>
        
        <input id="antialias-toggler" type="checkbox" />
    </div>
    
    <div class="Panel-row">
        <label for="physical-lights-toggler" class="Panel-text">
            Luzes físicas
        </label>
        
        <input id="physical-lights-toggler" type="checkbox" />
    </div>
    
    <div class="Panel-row">
        <label for="shadow-toggler" class="Panel-text">
            Sombras
        </label>
        
        <input id="shadow-toggler" type="checkbox" />
        
        <select id="shadow-type-selector" autocomplete="off" name="shadow_type">
            <?php foreach ( $shadow_types as $label => $value ) : ?>
                <option value="<?php echo $value ?>">
                    <?php echo $label ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
    
    <div class="Panel-row">
        <label for="tone-mapping-selector" class="Panel-text">
            Mapeamento dos tons
        </label> 
        
        <select id="tone-mapping-selector" name="tone_mapping" autocomplete="off">
            <?php foreach ( $tone_mapping_types as $label => $value ) : ?>
                <option value="<?php echo $value ?>">
                    <?php echo $label ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
    
    <div class="Panel-row" for-select="tone-mapping-selector" show-when-value-not="0" style="display: none;">
        <label for="tone-mapping-exposure" class="Panel-text">
            Exposição dos tons
        </label>
    
        <input  
            id="tone-mapping-exposure" 
            type="number" 
            step="0.1" 
            autocomplete="off"
            style="flex: none; width: 15%;" 
        />
    </div>
</div>

<div class="Panel" style="padding: 10px 0 0 0;">
    <div class="Panel-row" style="margin-bottom: 0;">
    </div>
</div> 