<div class="Panel">
    <div class="Panel-row">
        <label for="ctx-selector" class="Panel-text">
            Cena
        </label>
        <select id="ctx-selector" autocomplete="off"></select>
        <div 
            id="delete-scene-btn"
            class="Panel-button" 
            title="<?php echo htmlentities($help_texts["deleteSceneBtn"], ENT_QUOTES, "UTF-8") ?>"
        >
            <i class="fa fa-trash-o" aria-hidden="true"></i>
        </div>
        <div 
            id="add-scene-btn"
            class="Panel-button" 
            title="<?php echo htmlentities($help_texts["newSceneBtn"], ENT_QUOTES, "UTF-8") ?>"
        >
            <i class="fa fa-plus" aria-hidden="true"></i>
        </div>
    </div>
    <div class="Panel-row">
        <label for="ctx-name" class="Panel-text"> 
            Nome
        </label>
        <input id="ctx-name" type="text" />
    </div>
    <div class="Panel-row">
        <label 
            for="opacity-factor" 
            class="Panel-text" 
            title="<?php echo htmlentities($help_texts["opacityFactor"], ENT_QUOTES, "UTF-8") ?>"
        > 
            Fator de transparência 
        </label>
        <input 
            id="opacity-factor"
            class="Panel-item--is16"
            type="number" 
            min="0" 
            max="1"
            step="0.1" 
        />
    </div>
    <div class="Panel-row">
        <label 
            for="scene-render-order" 
            class="Panel-text" 
            title="<?php echo htmlentities($help_texts["sceneRenderOrder"], ENT_QUOTES, "UTF-8") ?>"
        > 
            Ordem de renderização
        </label>
        <input 
            id="scene-render-order"
            class="Panel-item--is16"
            type="number" 
            min="0" 
            max="2"
            step="1" 
        />
    </div>

</div>
    
<ul class="Tabs">
    <li class="Tabs-tabItem">
        <a href="#scene-background">
            <i class="Tabs-tabItem-arrow"></i>
            <span>Pano de fundo</span>
        </a>
        <div id="bg-selector-panel" class="Tabs-tabPanel Panel">
            <?php require "selectors/BackgroundSelector.phtml"; ?>
        </div>
    </li>
    <li class="Tabs-tabItem">
        <a href="#scene-env">
            <i class="Tabs-tabItem-arrow"></i>
            <span>Mapa de ambiente</span>
        </a>
        <div id="env-map-selector-panel" class="Tabs-tabPanel Panel">
            <?php require "selectors/EnvMapSelector.phtml"; ?>
        </div>
    </li>
    <li class="Tabs-tabItem">
        <a href="#scene-fog">
            <i class="Tabs-tabItem-arrow"></i>
            <span>Neblina</span>
        </a>
        <div id="fog-selector-panel" class="Tabs-tabPanel Panel">
            <?php require "selectors/FogSelector.phtml"; ?>
        </div>
    </li>
</ul>