<div class="Panel-row" id="<?php echo "$scope-{$row["attribute"]}-row" ?>" style="display: none;">
    <span class="Panel-text"    
        <?php if ( isset($help_texts[ $row["attribute"] ]) ) : ?>
            title="<?php echo htmlentities($help_texts[ $row["attribute"] ], ENT_QUOTES, "UTF-8") ?>"
        <?php endif; ?>    
    >
        <?php echo $row["label"] ?>
    </span>
    <input 
        autocomplete="off" type="number"
        style="flex: none; width: 20%;"
        step="<?php echo $row["step"] ?>"
        
        data-type="<?php echo $row["data_type"] ?>" 
        data-scope="<?php echo $scope ?>" 
        data-option="<?php echo "{$row["attribute"]}X" ?>"
        
        <?php if ( isset($row["max"]) && !is_null($row["max"]) ) : ?> 
            max="<?php echo $row["max"] ?>" 
        <?php endif; ?>
        <?php if ( isset($row["min"]) && !is_null($row["min"]) ) : ?> 
            min="<?php echo $row["min"] ?>" 
        <?php endif; ?>
    />
    <input 
        autocomplete="off" type="number"
        style="flex: none; width: 20%;"
        step="<?php echo $row["step"] ?>"
        
        data-type="<?php echo $row["data_type"] ?>" 
        data-scope="<?php echo $scope ?>" 
        data-option="<?php echo "{$row["attribute"]}Y" ?>"
        
        <?php if ( isset($row["max"]) && !is_null($row["max"]) ) : ?> 
            max="<?php echo $row["max"] ?>" 
        <?php endif; ?>
        <?php if ( isset($row["min"]) && !is_null($row["min"]) ) : ?> 
            min="<?php echo $row["min"] ?>" 
        <?php endif; ?>
    />
    <input 
        autocomplete="off" type="number"
        style="flex: none; width: 20%;"
        step="<?php echo $row["step"] ?>"
        
        data-type="<?php echo $row["data_type"] ?>" 
        data-scope="<?php echo $scope ?>" 
        data-option="<?php echo "{$row["attribute"]}Z" ?>"
        
        <?php if ( isset($row["max"]) && !is_null($row["max"]) ) : ?> 
            max="<?php echo $row["max"] ?>" 
        <?php endif; ?>
        <?php if ( isset($row["min"]) && !is_null($row["min"]) ) : ?> 
            min="<?php echo $row["min"] ?>" 
        <?php endif; ?>
    />
</div>