<div class="Panel-row" id="<?php echo "$scope-{$row["attribute"]}-row" ?>" style="display: none;">
    <label  
        for="<?php echo "$scope-{$row["attribute"]}-field" ?>" 
        class="Panel-text"
        <?php if ( isset($help_texts[ $row["attribute"] ]) ) : ?>
            title="<?php echo htmlentities($help_texts[ $row["attribute"] ], ENT_QUOTES, "UTF-8") ?>"
        <?php endif; ?>
    >
        <?php echo $row["label"] ?>
    </label>
    <input
        id="<?php echo "$scope-{$row["attribute"]}-field" ?>" 
        type="number" 
        style="flex: none; width: 20%;"
        step="<?php echo $row["data_type"] == "Float" ? "0.01" : "1"?>"
        
        data-scope="<?php echo $scope ?>" 
        data-type="<?php echo $row["data_type"] ?>" 
        data-option="<?php echo $row["attribute"] ?>"
        
        <?php if ( isset($row["max"]) && !is_null($row["max"]) ) : ?> 
            max="<?php echo $row["max"] ?>"
        <?php endif; ?>
        <?php if ( isset($row["min"]) && !is_null($row["min"]) ) : ?> 
            min="<?php echo $row["min"] ?>" 
        <?php endif; ?>
    />
</div>